In [1]:
import pandas as pd
df= pd.read_csv('survey_results_public.csv')

In [2]:
pd.set_option("display.max_columns", 85)

In [3]:
df.head(1)

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult

In [4]:
df.columns

Index(['Respondent', 'MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource',
       'Employment', 'Country', 'Student', 'EdLevel', 'UndergradMajor',
       'EduOther', 'OrgSize', 'DevType', 'YearsCode', 'Age1stCode',
       'YearsCodePro', 'CareerSat', 'JobSat', 'MgrIdiot', 'MgrMoney',
       'MgrWant', 'JobSeek', 'LastHireDate', 'LastInt', 'FizzBuzz',
       'JobFactors', 'ResumeUpdate', 'CurrencySymbol', 'CurrencyDesc',
       'CompTotal', 'CompFreq', 'ConvertedComp', 'WorkWeekHrs', 'WorkPlan',
       'WorkChallenge', 'WorkRemote', 'WorkLoc', 'ImpSyn', 'CodeRev',
       'CodeRevHrs', 'UnitTests', 'PurchaseHow', 'PurchaseWhat',
       'LanguageWorkedWith', 'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'WebFrameWorkedWith',
       'WebFrameDesireNextYear', 'MiscTechWorkedWith',
       'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers',
       'BlockchainOrg', 'BlockchainIs', 'BetterLife', 'ITperson', 'OffOn',
       'SocialMedia', 'Extraversion', 'ScreenName', 'SOVisit1st',
       'SOVisitFreq', 'SOVisitTo', 'SOFindAnswer', 'SOTimeSaved',
       'SOHowMuchTime', 'SOAccount', 'SOPartFreq', 'SOJobs', 'EntTeams',
       'SOComm', 'WelcomeChange', 'SONewContent', 'Age', 'Gender', 'Trans',
       'Sexuality', 'Ethnicity', 'Dependents', 'SurveyLength', 'SurveyEase'],
      dtype='object')

In [5]:
df['ConvertedComp'].median()

57287.0

In [7]:
df['Hobbyist'].value_counts()

Yes    71257
No     17626
Name: Hobbyist, dtype: int64

In [8]:
df['Gender'].value_counts()

Man                                                            77919
Woman                                                           6344
Non-binary, genderqueer, or gender non-conforming                597
Man;Non-binary, genderqueer, or gender non-conforming            181
Woman;Non-binary, genderqueer, or gender non-conforming          163
Woman;Man                                                        132
Woman;Man;Non-binary, genderqueer, or gender non-conforming       70
Name: Gender, dtype: int64

In [9]:
df['SocialMedia'].value_counts()

Reddit                      14374
YouTube                     13830
WhatsApp                    13347
Facebook                    13178
Twitter                     11398
Instagram                    6261
I don't use social media     5554
LinkedIn                     4501
WeChat 微信                     667
Snapchat                      628
VK ВКонта́кте                 603
Weibo 新浪微博                     56
Youku Tudou 优酷                 21
Hello                          19
Name: SocialMedia, dtype: int64

In [10]:
df.groupby('Country')['SocialMedia'].value_counts()

Country      SocialMedia
Afghanistan  Facebook                    15
             YouTube                      9
             I don't use social media     6
             WhatsApp                     4
             Instagram                    1
                                         ..
Zimbabwe     Facebook                     3
             YouTube                      3
             Instagram                    2
             LinkedIn                     2
             Reddit                       1
Name: SocialMedia, Length: 1220, dtype: int64

In [11]:
df.groupby('Country')['SocialMedia'].value_counts().loc['India']

SocialMedia
WhatsApp                    2990
YouTube                     1820
LinkedIn                     955
Facebook                     841
Instagram                    822
Twitter                      542
Reddit                       473
I don't use social media     250
Snapchat                      23
Hello                          5
WeChat 微信                      5
VK ВКонта́кте                  4
Youku Tudou 优酷                 2
Weibo 新浪微博                     1
Name: SocialMedia, dtype: int64

In [12]:
df.groupby('Country')['SocialMedia'].value_counts().loc['Canada']

SocialMedia
Reddit                      901
YouTube                     526
Facebook                    515
Twitter                     405
Instagram                   246
I don't use social media    232
WhatsApp                    185
LinkedIn                    179
WeChat 微信                    44
Snapchat                     28
VK ВКонта́кте                 7
Weibo 新浪微博                    1
Name: SocialMedia, dtype: int64

In [13]:
df.groupby('Country')['ConvertedComp'].median()

Country
Afghanistan                               6222.0
Albania                                  10818.0
Algeria                                   7878.0
Andorra                                 160931.0
Angola                                    7764.0
                                          ...
Venezuela, Bolivarian Republic of...      6384.0
Viet Nam                                 11892.0
Yemen                                    11940.0
Zambia                                    5040.0
Zimbabwe                                 19200.0
Name: ConvertedComp, Length: 179, dtype: float64

In [14]:
df.groupby('Country')['ConvertedComp'].median().loc['Zimbabwe']

19200.0

In [15]:
df.groupby('Country')['ConvertedComp'].agg(['median','mean'])

                                        median           mean
Country
Afghanistan                             6222.0  101953.333333
Albania                                10818.0   21833.700000
Algeria                                 7878.0   34924.047619
Andorra                               160931.0  160931.000000
Angola                                  7764.0    7764.000000
...                                        ...            ...
Venezuela, Bolivarian Republic of...    6384.0   14581.627907
Viet Nam                               11892.0   17233.436782
Yemen                                  11940.0   16909.166667
Zambia                                  5040.0   10075.375000
Zimbabwe                               19200.0   34046.666667

[179 rows x 2 columns]

In [16]:
df.groupby('Country')['ConvertedComp'].agg(['median','mean']).loc['United Kingdom']

median     68041.000000
mean      166182.499504
Name: United Kingdom, dtype: float64

In [17]:
wdf = pd.read_csv('Weather Data.csv')
wdf.head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog

In [18]:
wdf['Wind Speed_km/h'].unique()

array([ 4,  7,  6,  9, 15, 13, 20, 22, 19, 24, 30, 35, 39, 32, 33, 26, 44,
       43, 48, 37, 28, 17, 11,  0, 83, 70, 57, 46, 41, 52, 50, 63, 54,  2],
      dtype=int64)

In [23]:
filt = wdf['Weather'] == 'Clear'
len(wdf[filt])

1326

In [26]:
len(wdf.groupby('Weather').get_group('Clear'))

1326

In [27]:
filt = wdf['Wind Speed_km/h']==4
len(wdf[filt])

474

In [28]:
wdf.groupby('Wind Speed_km/h').get_group(4)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
96,1/5/2012 0:00,-8.8,-11.7,79,4,9.7,100.32,Snow
101,1/5/2012 5:00,-7.0,-9.5,82,4,4.0,100.19,Snow
146,1/7/2012 2:00,-8.1,-11.1,79,4,19.3,100.15,Cloudy
...,...,...,...,...,...,...,...,...
8768,12/31/2012 8:00,-8.6,-10.3,87,4,3.2,101.14,Snow Showers
8769,12/31/2012 9:00,-8.1,-9.6,89,4,2.4,101.09,Snow
8770,12/31/2012 10:00,-7.4,-8.9,89,4,6.4,101.05,"Snow,Fog"
8772,12/31/2012 12:00,-5.8,-7.5,88,4,12.9,100.78,Snow
8773,12/31/2012 13:00,-4.6,-6.6,86,4,12.9,100.63,Snow

In [30]:
wdf.isnull().sum()

Date/Time           0
Temp_C              0
Dew Point Temp_C    0
Rel Hum_%           0
Wind Speed_km/h     0
Visibility_km       0
Press_kPa           0
Weather             0
dtype: int64

In [33]:
wdf.rename(columns = {'Weather':'Weather Condition'}, inplace=True)
wdf

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog
...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [35]:
wdf['Visibility_km'].mean()

27.66444672131151

In [36]:
wdf['Press_kPa'].std()

0.8440047459486474

In [37]:
wdf['Rel Hum_%'].var()

286.2485501984998

In [38]:
filt = wdf['Weather Condition'] == 'Snow'
wdf[filt]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
55,1/3/2012 7:00,-14.0,-19.5,63,19,25.0,100.95,Snow
84,1/4/2012 12:00,-13.7,-21.7,51,11,24.1,101.25,Snow
86,1/4/2012 14:00,-11.3,-19.0,53,7,19.3,100.97,Snow
87,1/4/2012 15:00,-10.2,-16.3,61,11,9.7,100.89,Snow
88,1/4/2012 16:00,-9.4,-15.5,61,13,19.3,100.79,Snow
...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [39]:
wdf.groupby('Weather Condition').get_group('Snow')

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
55,1/3/2012 7:00,-14.0,-19.5,63,19,25.0,100.95,Snow
84,1/4/2012 12:00,-13.7,-21.7,51,11,24.1,101.25,Snow
86,1/4/2012 14:00,-11.3,-19.0,53,7,19.3,100.97,Snow
87,1/4/2012 15:00,-10.2,-16.3,61,11,9.7,100.89,Snow
88,1/4/2012 16:00,-9.4,-15.5,61,13,19.3,100.79,Snow
...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [48]:
filt = (wdf['Wind Speed_km/h'] > 24) & (wdf['Visibility_km']==25)

In [49]:
wdf[filt]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
23,1/1/2012 23:00,5.3,2.0,79,30,25.0,99.31,Cloudy
24,1/2/2012 0:00,5.2,1.5,77,35,25.0,99.26,Rain Showers
25,1/2/2012 1:00,4.6,0.0,72,39,25.0,99.26,Cloudy
26,1/2/2012 2:00,3.9,-0.9,71,32,25.0,99.26,Mostly Cloudy
27,1/2/2012 3:00,3.7,-1.5,69,33,25.0,99.30,Mostly Cloudy
...,...,...,...,...,...,...,...,...
8705,12/28/2012 17:00,-8.6,-12.0,76,26,25.0,101.34,Mainly Clear
8753,12/30/2012 17:00,-12.1,-15.8,74,28,25.0,101.26,Mainly Clear
8755,12/30/2012 19:00,-13.4,-16.5,77,26,25.0,101.47,Mainly Clear
8759,12/30/2012 23:00,-12.1,-15.1,78,28,25.0,101.52,Mostly Cloudy
8760,12/31/2012 0:00,-11.1,-14.4,77,26,25.0,101.51,Cloudy

In [50]:
wdf.groupby('Weather Condition').mean()

,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa
Weather Condition,,,,,,
Clear,6.825716,0.089367,64.497738,10.557315,30.153243,101.587443
Cloudy,7.970544,2.375810,69.592593,16.127315,26.625752,100.911441
Drizzle,7.353659,5.504878,88.243902,16.097561,17.931707,100.435366
"Drizzle,Fog",8.067500,7.033750,93.275000,11.862500,5.257500,100.786625
"Drizzle,Ice Pellets,Fog",0.400000,-0.700000,92.000000,20.000000,4.000000,100.790000
"Drizzle,Snow",1.050000,0.150000,93.500000,14.000000,10.500000,100.890000
"Drizzle,Snow,Fog",0.693333,0.120000,95.866667,15.533333,5.513333,99.281333
Fog,4.303333,3.159333,92.286667,7.946667,6.248000,101.184067
Freezing Drizzle,-5.657143,-8.000000,83.571429,16.571429,9.200000,100.202857
"Freezing Drizzle,Fog",-2.533333,-4.183333,88.500000,17.000000,5.266667,100.441667
"Freezing Drizzle,Haze",-5.433333,-8.000000,82.000000,10.333333,2.666667,100.316667
"Freezing Drizzle,Snow",-5.109091,-7.072727,86.090909,16.272727,5.872727,100.520909
Freezing Fog,-7.575000,-9.250000,87.750000,4.750000,0.650000,102.320000
Freezing Rain,-3.885714,-6.078571,84.642857,19.214286,8.242857,99.647143
"Freezing Rain,Fog",-2.225000,-3.750000,89.500000,15.500000,7.550000,99.945000
"Freezing Rain,Haze",-4.900000,-7.450000,82.500000,7.500000,2.400000,100.375000
"Freezing Rain,Ice Pellets,Fog",-2.600000,-3.700000,92.000000,28.000000,8.000000,100.950000
"Freezing Rain,Snow Grains",-5.000000,-7.300000,84.000000,32.000000,4.800000,98.560000
Haze,-0.200000,-2.975000,81.625000,10.437500,7.831250,101.482500
Mainly Clear,12.558927,4.581671,60.667142,14.144824,34.264862,101.248832
"Moderate Rain,Fog",1.700000,0.800000,94.000000,17.000000,6.400000,99.980000
Moderate Snow,-5.525000,-7.250000,87.750000,33.750000,0.750000,100.275000
"Moderate Snow,Blowing Snow",-5.450000,-6.500000,92.500000,40.000000,0.600000,100.570000
Mostly Cloudy,10.574287,3.131174,62.102465,15.813920,31.253842,101.025288
Rain,9.786275,7.042810,83.624183,19.254902,18.856536,100.233333
Rain Showers,13.722340,9.187766,75.159574,17.132979,22.816489,100.404043
"Rain Showers,Fog",12.800000,12.100000,96.000000,13.000000,6.400000,99.830000
"Rain Showers,Snow Showers",2.150000,-1.500000,76.500000,22.500000,21.700000,101.100000
"Rain,Fog",8.273276,7.219828,93.189655,14.793103,6.873276,100.500862
"Rain,Haze",4.633333,2.066667,83.333333,11.666667,6.700000,100.540000
"Rain,Ice Pellets",0.600000,-0.600000,92.000000,24.000000,9.700000,100.120000
"Rain,Snow",1.055556,-0.566667,89.000000,28.388889,11.672222,99.951111
"Rain,Snow Grains",1.900000,-2.100000,75.000000,26.000000,25.000000,100.600000
"Rain,Snow,Fog",0.800000,0.300000,96.000000,9.000000,6.400000,100.730000
"Rain,Snow,Ice Pellets",1.100000,-0.175000,91.500000,23.250000,6.000000,100.105000
Snow,-4.524103,-7.623333,79.307692,20.038462,11.171795,100.536103
Snow Pellets,0.700000,-6.400000,59.000000,35.000000,2.400000,99.700000
Snow Showers,-3.506667,-7.866667,72.350000,19.233333,20.158333,100.963500
"Snow Showers,Fog",-10.675000,-11.900000,90.750000,13.750000,7.025000,101.292500
"Snow,Blowing Snow",-5.410526,-7.621053,84.473684,34.842105,4.105263,99.704737
"Snow,Fog",-5.075676,-6.364865,90.675676,17.324324,4.537838,100.688649
"Snow,Haze",-4.020000,-6.860000,80.600000,5.000000,4.640000,100.782000
"Snow,Ice Pellets",-1.883333,-3.666667,87.666667,23.833333,7.416667,100.548333
Thunderstorms,24.150000,19.750000,77.000000,7.500000,24.550000,100.230000
"Thunderstorms,Heavy Rain Showers",10.900000,9.000000,88.000000,9.000000,2.400000,100.260000
"Thunderstorms,Moderate Rain Showers,Fog",19.600000,18.500000,93.000000,15.000000,3.200000,100.010000
"Thunderstorms,Rain",20.433333,18.533333,89.000000,15.666667,19.833333,100.420000
"Thunderstorms,Rain Showers",20.037500,17.618750,86.375000,18.312500,15.893750,100.233750
"Thunderstorms,Rain Showers,Fog",21.600000,18.700000,84.000000,19.666667,9.700000,100.063333
"Thunderstorms,Rain,Fog",20.600000,18.600000,88.000000,19.000000,4.800000,100.080000

In [51]:
wdf.groupby('Weather Condition').mean().loc['Clear']

Temp_C                6.825716
Dew Point Temp_C      0.089367
Rel Hum_%            64.497738
Wind Speed_km/h      10.557315
Visibility_km        30.153243
Press_kPa           101.587443
Name: Clear, dtype: float64

In [52]:
wdf.groupby('Weather Condition').max()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa
Weather Condition,,,,,,,
Clear,9/9/2012 5:00,32.8,20.4,99,33,48.3,103.63
Cloudy,9/9/2012 23:00,30.5,22.6,99,54,48.3,103.65
Drizzle,9/30/2012 3:00,18.8,17.7,96,30,25.0,101.56
"Drizzle,Fog",9/30/2012 2:00,19.9,19.1,100,28,9.7,102.07
"Drizzle,Ice Pellets,Fog",12/17/2012 9:00,0.4,-0.7,92,20,4.0,100.79
"Drizzle,Snow",12/19/2012 18:00,1.2,0.2,95,19,11.3,101.15
"Drizzle,Snow,Fog",12/22/2012 3:00,1.1,0.6,98,32,9.7,100.15
Fog,9/22/2012 0:00,20.8,19.6,100,22,9.7,103.04
Freezing Drizzle,2/1/2012 5:00,-2.3,-3.3,93,26,12.9,101.02
"Freezing Drizzle,Fog",12/10/2012 5:00,-0.3,-2.3,94,33,8.0,101.27
"Freezing Drizzle,Haze",2/1/2012 13:00,-5.0,-7.7,83,11,4.0,100.36
"Freezing Drizzle,Snow",3/2/2012 12:00,-3.3,-4.6,94,24,12.9,101.18
Freezing Fog,3/17/2012 6:00,-0.1,-0.3,99,9,0.8,102.85
Freezing Rain,2/1/2012 7:00,0.3,-1.7,92,28,16.1,101.00
"Freezing Rain,Fog",12/17/2012 1:00,0.1,-0.9,93,26,9.7,101.01
"Freezing Rain,Haze",2/1/2012 15:00,-4.9,-7.4,83,9,2.8,100.41
"Freezing Rain,Ice Pellets,Fog",12/17/2012 3:00,-2.6,-3.7,92,28,8.0,100.95
"Freezing Rain,Snow Grains",1/13/2012 9:00,-5.0,-7.3,84,32,4.8,98.56
Haze,3/13/2012 23:00,14.1,11.1,86,17,9.7,102.97
Mainly Clear,9/9/2012 9:00,33.0,21.2,99,63,48.3,103.59
"Moderate Rain,Fog",12/10/2012 8:00,1.7,0.8,94,17,6.4,99.98
Moderate Snow,12/27/2012 9:00,-4.9,-6.7,93,39,0.8,100.67
"Moderate Snow,Blowing Snow",12/27/2012 12:00,-5.4,-6.4,93,41,0.6,100.64
Mostly Cloudy,9/9/2012 2:00,32.4,24.4,100,83,48.3,103.65
Rain,9/5/2012 2:00,22.8,20.4,99,52,48.3,102.26
Rain Showers,9/8/2012 16:00,26.4,23.0,97,41,48.3,102.31
"Rain Showers,Fog",10/20/2012 3:00,12.8,12.1,96,13,6.4,99.83
"Rain Showers,Snow Showers",12/5/2012 10:00,2.2,-1.2,78,28,24.1,101.11
"Rain,Fog",9/30/2012 23:00,21.7,19.5,100,46,9.7,101.77
"Rain,Haze",3/13/2012 9:00,5.5,2.9,86,17,9.7,100.61
"Rain,Ice Pellets",12/18/2012 5:00,0.6,-0.6,92,24,9.7,100.12
"Rain,Snow",4/23/2012 3:00,1.7,0.5,94,52,25.0,101.07
"Rain,Snow Grains",12/21/2012 0:00,1.9,-2.1,75,26,25.0,100.60
"Rain,Snow,Fog",12/8/2012 21:00,0.8,0.3,96,9,6.4,100.73
"Rain,Snow,Ice Pellets",12/21/2012 5:00,1.3,0.1,94,28,6.4,100.47
Snow,4/27/2012 9:00,3.7,0.3,96,57,25.0,102.73
Snow Pellets,11/24/2012 15:00,0.7,-6.4,59,35,2.4,99.70
Snow Showers,3/4/2012 21:00,2.9,-0.7,94,37,48.3,102.50
"Snow Showers,Fog",12/29/2012 13:00,-10.0,-11.1,92,22,9.7,102.52
"Snow,Blowing Snow",2/25/2012 9:00,-1.4,-2.9,91,48,9.7,100.62
"Snow,Fog",3/14/2012 19:00,1.1,0.8,99,35,9.7,102.07
"Snow,Haze",2/1/2012 21:00,-3.6,-6.4,81,15,6.4,100.99
"Snow,Ice Pellets",3/3/2012 4:00,0.8,-1.7,92,33,11.3,100.96
Thunderstorms,7/4/2012 16:00,26.7,20.1,87,15,25.0,100.62
"Thunderstorms,Heavy Rain Showers",5/29/2012 6:00,10.9,9.0,88,9,2.4,100.26
"Thunderstorms,Moderate Rain Showers,Fog",7/17/2012 6:00,19.6,18.5,93,15,3.2,100.01
"Thunderstorms,Rain",7/23/2012 18:00,21.3,19.1,93,30,24.1,100.83
"Thunderstorms,Rain Showers",9/8/2012 4:00,25.5,23.1,98,32,25.0,101.06
"Thunderstorms,Rain Showers,Fog",7/31/2012 20:00,22.9,21.3,91,35,9.7,100.64
"Thunderstorms,Rain,Fog",7/17/2012 5:00,20.6,18.6,88,19,4.8,100.08

In [53]:
wdf.groupby('Weather Condition').min()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa
Weather Condition,,,,,,,
Clear,1/11/2012 1:00,-23.3,-28.5,20,0,11.3,99.52
Cloudy,1/1/2012 17:00,-21.4,-26.8,18,0,11.3,98.39
Drizzle,1/23/2012 21:00,1.1,-0.2,74,0,6.4,97.84
"Drizzle,Fog",1/23/2012 20:00,0.0,-1.6,85,0,1.0,98.65
"Drizzle,Ice Pellets,Fog",12/17/2012 9:00,0.4,-0.7,92,20,4.0,100.79
"Drizzle,Snow",12/17/2012 15:00,0.9,0.1,92,9,9.7,100.63
"Drizzle,Snow,Fog",12/18/2012 21:00,0.3,-0.1,92,7,2.4,97.79
Fog,1/1/2012 0:00,-16.0,-17.2,80,0,0.2,98.31
Freezing Drizzle,1/13/2012 10:00,-9.0,-12.2,78,6,4.8,98.44
"Freezing Drizzle,Fog",1/1/2012 2:00,-6.4,-9.0,82,6,3.6,98.74
"Freezing Drizzle,Haze",2/1/2012 11:00,-5.8,-8.3,81,9,2.0,100.28
"Freezing Drizzle,Snow",1/13/2012 3:00,-8.3,-10.4,79,6,2.4,99.19
Freezing Fog,1/22/2012 6:00,-19.0,-22.9,71,0,0.2,101.97
Freezing Rain,1/13/2012 11:00,-6.5,-9.0,81,7,2.8,98.22
"Freezing Rain,Fog",1/17/2012 23:00,-6.1,-8.7,82,7,2.8,98.32
"Freezing Rain,Haze",2/1/2012 14:00,-4.9,-7.5,82,6,2.0,100.34
"Freezing Rain,Ice Pellets,Fog",12/17/2012 3:00,-2.6,-3.7,92,28,8.0,100.95
"Freezing Rain,Snow Grains",1/13/2012 9:00,-5.0,-7.3,84,32,4.8,98.56
Haze,1/22/2012 12:00,-11.5,-16.0,68,0,4.8,100.35
Mainly Clear,1/10/2012 11:00,-22.8,-28.0,20,0,12.9,98.67
"Moderate Rain,Fog",12/10/2012 8:00,1.7,0.8,94,17,6.4,99.98
Moderate Snow,1/12/2012 15:00,-6.3,-7.6,83,26,0.6,99.88
"Moderate Snow,Blowing Snow",12/27/2012 10:00,-5.5,-6.6,92,39,0.6,100.50
Mostly Cloudy,1/1/2012 16:00,-23.2,-28.5,18,0,11.3,98.36
Rain,1/1/2012 18:00,0.3,-5.7,40,0,4.0,97.52
Rain Showers,1/1/2012 22:00,1.6,-7.2,37,0,6.4,98.51
"Rain Showers,Fog",10/20/2012 3:00,12.8,12.1,96,13,6.4,99.83
"Rain Showers,Snow Showers",11/4/2012 8:00,2.1,-1.8,75,17,19.3,101.09
"Rain,Fog",1/23/2012 18:00,0.0,-1.2,83,0,2.0,98.61
"Rain,Haze",3/13/2012 7:00,4.0,1.0,81,7,4.0,100.50
"Rain,Ice Pellets",12/18/2012 5:00,0.6,-0.6,92,24,9.7,100.12
"Rain,Snow",1/10/2012 5:00,0.6,-1.7,81,13,2.4,98.18
"Rain,Snow Grains",12/21/2012 0:00,1.9,-2.1,75,26,25.0,100.60
"Rain,Snow,Fog",12/8/2012 21:00,0.8,0.3,96,9,6.4,100.73
"Rain,Snow,Ice Pellets",12/21/2012 1:00,0.9,-0.7,88,17,4.8,99.85
Snow,1/10/2012 1:00,-16.7,-24.6,41,0,1.0,97.75
Snow Pellets,11/24/2012 15:00,0.7,-6.4,59,35,2.4,99.70
Snow Showers,1/12/2012 7:00,-13.3,-19.3,52,0,2.4,99.49
"Snow Showers,Fog",12/26/2012 9:00,-11.3,-12.7,89,7,4.0,100.63
"Snow,Blowing Snow",1/13/2012 21:00,-12.0,-16.2,70,24,0.6,98.11
"Snow,Fog",12/16/2012 15:00,-10.1,-12.0,77,4,1.2,99.38
"Snow,Haze",2/1/2012 17:00,-4.3,-7.2,80,0,4.0,100.61
"Snow,Ice Pellets",12/10/2012 3:00,-4.3,-5.9,76,19,2.8,99.40
Thunderstorms,7/16/2012 1:00,21.6,19.4,67,0,24.1,99.84
"Thunderstorms,Heavy Rain Showers",5/29/2012 6:00,10.9,9.0,88,9,2.4,100.26
"Thunderstorms,Moderate Rain Showers,Fog",7/17/2012 6:00,19.6,18.5,93,15,3.2,100.01
"Thunderstorms,Rain",5/25/2012 20:00,19.4,18.2,83,4,16.1,100.19
"Thunderstorms,Rain Showers",5/29/2012 16:00,11.0,7.0,68,7,6.4,99.65
"Thunderstorms,Rain Showers,Fog",6/29/2012 3:00,19.5,16.1,80,7,9.7,99.71
"Thunderstorms,Rain,Fog",7/17/2012 5:00,20.6,18.6,88,19,4.8,100.08

In [54]:
wdf.groupby('Weather Condition').get_group('Fog')

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog
5,1/1/2012 5:00,-1.4,-3.3,87,9,6.4,101.27,Fog
6,1/1/2012 6:00,-1.5,-3.1,89,7,6.4,101.29,Fog
...,...,...,...,...,...,...,...,...
8716,12/29/2012 4:00,-16.0,-17.2,90,6,9.7,101.25,Fog
8717,12/29/2012 5:00,-14.8,-15.9,91,4,6.4,101.25,Fog
8718,12/29/2012 6:00,-13.8,-15.3,88,4,9.7,101.25,Fog
8719,12/29/2012 7:00,-14.8,-16.4,88,7,8.0,101.22,Fog
8722,12/29/2012 10:00,-12.0,-13.3,90,7,6.4,101.15,Fog

In [58]:
filt = (wdf['Weather Condition'] == 'Clear') | (wdf['Visibility_km'] > 40)
wdf[filt]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
67,1/3/2012 19:00,-16.9,-24.8,50,24,25.0,101.74,Clear
106,1/5/2012 10:00,-6.0,-10.0,73,17,48.3,100.45,Mainly Clear
107,1/5/2012 11:00,-5.6,-10.2,70,22,48.3,100.41,Mainly Clear
108,1/5/2012 12:00,-4.7,-9.6,69,20,48.3,100.38,Mainly Clear
109,1/5/2012 13:00,-4.4,-9.7,66,26,48.3,100.40,Mainly Clear
...,...,...,...,...,...,...,...,...
8749,12/30/2012 13:00,-12.4,-16.2,73,37,48.3,100.92,Mostly Cloudy
8750,12/30/2012 14:00,-11.8,-16.1,70,37,48.3,100.96,Mainly Clear
8751,12/30/2012 15:00,-11.3,-15.6,70,32,48.3,101.05,Mainly Clear
8752,12/30/2012 16:00,-11.4,-15.5,72,26,48.3,101.15,Mainly Clear
8756,12/30/2012 20:00,-13.8,-16.5,80,24,25.0,101.52,Clear

In [59]:
filt = (wdf['Weather Condition'] == 'Clear') & (wdf['Rel Hum_%'] > 50)
wdf[filt]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
114,1/5/2012 18:00,-7.1,-14.4,56,11,25.0,100.71,Clear
115,1/5/2012 19:00,-9.2,-15.4,61,7,25.0,100.80,Clear
116,1/5/2012 20:00,-9.8,-15.7,62,9,25.0,100.83,Clear
117,1/5/2012 21:00,-9.0,-14.8,63,13,25.0,100.83,Clear
241,1/11/2012 1:00,-10.7,-17.8,56,17,25.0,101.49,Clear
...,...,...,...,...,...,...,...,...
8646,12/26/2012 6:00,-13.4,-14.8,89,4,25.0,102.47,Clear
8698,12/28/2012 10:00,-6.1,-8.6,82,19,24.1,101.27,Clear
8713,12/29/2012 1:00,-11.9,-13.6,87,11,25.0,101.31,Clear
8714,12/29/2012 2:00,-11.8,-13.1,90,13,25.0,101.33,Clear
8756,12/30/2012 20:00,-13.8,-16.5,80,24,25.0,101.52,Clear

In [60]:
filt = wdf['Visibility_km'] > 40
wdf[filt]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
106,1/5/2012 10:00,-6.0,-10.0,73,17,48.3,100.45,Mainly Clear
107,1/5/2012 11:00,-5.6,-10.2,70,22,48.3,100.41,Mainly Clear
108,1/5/2012 12:00,-4.7,-9.6,69,20,48.3,100.38,Mainly Clear
109,1/5/2012 13:00,-4.4,-9.7,66,26,48.3,100.40,Mainly Clear
110,1/5/2012 14:00,-5.1,-10.7,65,22,48.3,100.46,Mainly Clear
...,...,...,...,...,...,...,...,...
8748,12/30/2012 12:00,-12.2,-15.7,75,26,48.3,100.91,Mostly Cloudy
8749,12/30/2012 13:00,-12.4,-16.2,73,37,48.3,100.92,Mostly Cloudy
8750,12/30/2012 14:00,-11.8,-16.1,70,37,48.3,100.96,Mainly Clear
8751,12/30/2012 15:00,-11.3,-15.6,70,32,48.3,101.05,Mainly Clear
8752,12/30/2012 16:00,-11.4,-15.5,72,26,48.3,101.15,Mainly Clear

In [62]:
cdf = pd.read_csv('Cars Data1.csv')
cdf.head(2)

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265,17,23,4451,106,189
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200,24,31,2778,101,172

In [66]:
cdf.isnull().sum()

Make           0
Model          0
Type           0
Origin         0
DriveTrain     0
MSRP           0
Invoice        0
EngineSize     0
Cylinders      0
Horsepower     0
MPG_City       0
MPG_Highway    0
Weight         0
Wheelbase      0
Length         0
dtype: int64

In [64]:
m = cdf['Cylinders'].mean()
m

5.807511737089202

In [65]:
cdf['Cylinders'].fillna(m, inplace=True)

In [67]:
cdf['Make'].unique()

array(['Acura', 'Audi', 'BMW', 'Buick', 'Cadillac', 'Chevrolet',
       'Chrysler', 'Dodge', 'Ford', 'GMC', 'Honda', 'Hummer', 'Hyundai',
       'Infiniti', 'Isuzu', 'Jaguar', 'Jeep', 'Kia', 'Land Rover',
       'Lexus', 'Lincoln', 'MINI', 'Mazda', 'Mercedes-Benz', 'Mercury',
       'Mitsubishi', 'Nissan', 'Oldsmobile', 'Pontiac', 'Porsche', 'Saab',
       'Saturn', 'Scion', 'Subaru', 'Suzuki', 'Toyota', 'Volkswagen',
       'Volvo'], dtype=object)

In [68]:
cdf['Make'].value_counts()

Toyota           28
Chevrolet        27
Mercedes-Benz    26
Ford             23
BMW              20
Audi             19
Honda            17
Nissan           17
Volkswagen       15
Chrysler         15
Dodge            13
Mitsubishi       13
Hyundai          12
Volvo            12
Jaguar           12
Kia              11
Mazda            11
Pontiac          11
Subaru           11
Lexus            11
Lincoln           9
Mercury           9
Buick             9
Cadillac          8
Infiniti          8
Suzuki            8
GMC               8
Saturn            8
Porsche           7
Saab              7
Acura             7
Jeep              3
Land Rover        3
Oldsmobile        3
MINI              2
Scion             2
Isuzu             2
Hummer            1
Name: Make, dtype: int64

In [69]:
filt =(cdf['Origin']=='Asia') | (cdf['Origin']=='Europe')
cdf[filt]

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265,17,23,4451,106,189
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200,24,31,2778,101,172
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200,22,29,3230,105,183
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270,20,28,3575,108,186
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225,18,24,3880,115,197
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Front,"$40,565","$38,203",2.4,5.0,197,21,28,3450,105,186
424,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Front,"$42,565","$40,083",2.3,5.0,242,20,26,3450,105,186
425,Volvo,S80 T6 4dr,Sedan,Europe,Front,"$45,210","$42,573",2.9,6.0,268,19,26,3653,110,190
426,Volvo,V40,Wagon,Europe,Front,"$26,135","$24,641",1.9,4.0,170,22,29,2822,101,180
427,Volvo,XC70,Wagon,Europe,All,"$35,145","$33,112",2.5,5.0,208,20,27,3823,109,186

In [73]:
filt = cdf['Weight'] > 4000
cdf = cdf[~filt]
cdf

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200,24,31,2778,101,172
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200,22,29,3230,105,183
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270,20,28,3575,108,186
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225,18,24,3880,115,197
5,Acura,3.5 RL w/Navigation 4dr,Sedan,Asia,Front,"$46,100","$41,100",3.5,6.0,225,18,24,3893,115,197
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Front,"$40,565","$38,203",2.4,5.0,197,21,28,3450,105,186
424,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Front,"$42,565","$40,083",2.3,5.0,242,20,26,3450,105,186
425,Volvo,S80 T6 4dr,Sedan,Europe,Front,"$45,210","$42,573",2.9,6.0,268,19,26,3653,110,190
426,Volvo,V40,Wagon,Europe,Front,"$26,135","$24,641",1.9,4.0,170,22,29,2822,101,180
427,Volvo,XC70,Wagon,Europe,All,"$35,145","$33,112",2.5,5.0,208,20,27,3823,109,186

In [79]:
cdf['MPG_City'] = cdf['MPG_City'].apply(lambda x: x+3)
cdf

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
1,acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200,30,31,2778,101,172
2,acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200,28,29,3230,105,183
3,acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270,26,28,3575,108,186
4,acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225,24,24,3880,115,197
5,acura,3.5 RL w/Navigation 4dr,Sedan,Asia,Front,"$46,100","$41,100",3.5,6.0,225,24,24,3893,115,197
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423,volvo,C70 LPT convertible 2dr,Sedan,Europe,Front,"$40,565","$38,203",2.4,5.0,197,27,28,3450,105,186
424,volvo,C70 HPT convertible 2dr,Sedan,Europe,Front,"$42,565","$40,083",2.3,5.0,242,26,26,3450,105,186
425,volvo,S80 T6 4dr,Sedan,Europe,Front,"$45,210","$42,573",2.9,6.0,268,25,26,3653,110,190
426,volvo,V40,Wagon,Europe,Front,"$26,135","$24,641",1.9,4.0,170,28,29,2822,101,180
427,volvo,XC70,Wagon,Europe,All,"$35,145","$33,112",2.5,5.0,208,26,27,3823,109,186

In [80]:
cdf['Make'] = cdf['Make'].apply(lambda x: x.upper())
cdf

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
1,ACURA,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200,30,31,2778,101,172
2,ACURA,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200,28,29,3230,105,183
3,ACURA,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270,26,28,3575,108,186
4,ACURA,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225,24,24,3880,115,197
5,ACURA,3.5 RL w/Navigation 4dr,Sedan,Asia,Front,"$46,100","$41,100",3.5,6.0,225,24,24,3893,115,197
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423,VOLVO,C70 LPT convertible 2dr,Sedan,Europe,Front,"$40,565","$38,203",2.4,5.0,197,27,28,3450,105,186
424,VOLVO,C70 HPT convertible 2dr,Sedan,Europe,Front,"$42,565","$40,083",2.3,5.0,242,26,26,3450,105,186
425,VOLVO,S80 T6 4dr,Sedan,Europe,Front,"$45,210","$42,573",2.9,6.0,268,25,26,3653,110,190
426,VOLVO,V40,Wagon,Europe,Front,"$26,135","$24,641",1.9,4.0,170,28,29,2822,101,180
427,VOLVO,XC70,Wagon,Europe,All,"$35,145","$33,112",2.5,5.0,208,26,27,3823,109,186

### Task 1

In [82]:
cdf['Type'] = cdf['Type'].apply(lambda x: x.lower())
cdf

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
1,ACURA,RSX Type S 2dr,sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200,30,31,2778,101,172
2,ACURA,TSX 4dr,sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200,28,29,3230,105,183
3,ACURA,TL 4dr,sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270,26,28,3575,108,186
4,ACURA,3.5 RL 4dr,sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225,24,24,3880,115,197
5,ACURA,3.5 RL w/Navigation 4dr,sedan,Asia,Front,"$46,100","$41,100",3.5,6.0,225,24,24,3893,115,197
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423,VOLVO,C70 LPT convertible 2dr,sedan,Europe,Front,"$40,565","$38,203",2.4,5.0,197,27,28,3450,105,186
424,VOLVO,C70 HPT convertible 2dr,sedan,Europe,Front,"$42,565","$40,083",2.3,5.0,242,26,26,3450,105,186
425,VOLVO,S80 T6 4dr,sedan,Europe,Front,"$45,210","$42,573",2.9,6.0,268,25,26,3653,110,190
426,VOLVO,V40,wagon,Europe,Front,"$26,135","$24,641",1.9,4.0,170,28,29,2822,101,180
427,VOLVO,XC70,wagon,Europe,All,"$35,145","$33,112",2.5,5.0,208,26,27,3823,109,186

### Task 2

In [83]:
cdf.groupby(['Model','Cylinders']).mean()

,,EngineSize,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
Model,Cylinders,,,,,,,
3.5 RL 4dr,6.0,3.5,225.0,24.0,24.0,3880.0,115.0,197.0
3.5 RL w/Navigation 4dr,6.0,3.5,225.0,24.0,24.0,3893.0,115.0,197.0
300M 4dr,6.0,3.5,250.0,24.0,27.0,3581.0,113.0,198.0
300M Special Edition 4dr,6.0,3.5,255.0,24.0,27.0,3650.0,113.0,198.0
325Ci 2dr,6.0,2.5,184.0,26.0,29.0,3197.0,107.0,177.0
...,...,...,...,...,...,...,...,...
lon2 quad coupe 2dr,4.0,2.2,140.0,32.0,35.0,2751.0,103.0,185.0
lon3 4dr,4.0,2.2,140.0,32.0,35.0,2692.0,103.0,185.0
lon3 quad coupe 2dr,4.0,2.2,140.0,32.0,35.0,2751.0,103.0,185.0
xA 4dr hatch,4.0,1.5,108.0,38.0,38.0,2340.0,93.0,154.0
xB,4.0,1.5,108.0,37.0,35.0,2425.0,98.0,155.0